### ISSUE TITLE
Link mentioned in BSP-Android-NXP-i.MX8MP-ALPHA1.xml is inactive

### ISSUE THREAD

**Issue by anandprajapati7783** [phytec/phydroid#2]
We were able to sync the code before 1 month but now we are not able to sync the code right now, and it is showing the error the links are not accessible **BSP-Android-NXP-i.MX8MP-ALPHA1.xml**

**Comment by smk-embedded** [comment]
Hi, we are currently working on repairing all NXP builds, as they shut down their current git server. Which message do you get?

**Comment by wdmegrv** [comment]
Fixed with https://github.com/phytec/phydroid/commit/c5e05fb8a48604528baa417ced85d119aa570678
